#!/usr/bin/env bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
KIND_NAME="terraform-learn"
KIND_CURL="https://raw.githubusercontent.com/hashicorp/learn-terraform-deploy-nginx-kubernetes-provider/main/kind-config.yaml"

# Fetch a sample kind config
[ -f "kind-config.yaml" ] || curl -o kind-config.yaml $KIND_CURL

# Create a sample environment
if ! kind get clusters | grep $KIND_NAME > /dev/null; then
    kind create cluster --name $KIND_NAME --config kind-config.yaml
fi

# Switch to the newly create cluster
kubectl cluster-info --context "kind-$KIND_NAME"

# TODO: Fetch values from: kubectl config view --minify --flatten --context=kind-$KIND_NAME
cat <<- EOF
host                   = "https://127.0.0.1:32768"
client_certificate     = "..."
client_key             = "..."
cluster_ca_certificate = "..."
EOF

# Test commands
cd sample
terraform init 