# ------------------------------------------------------------
# This project is powered by: https://taskfile.dev
# ------------------------------------------------------------
version: 3
env: # <-- Project Configuration (required ENV vars)
  ENVIRONMENT: "{{ .ENVIRONMENT }}"
tasks:
  init: echo cd {{ .TASK_DIR }} -- terraform init
  plan: cd {{ .TASK_DIR }} && terraform plan
  apply: cd {{ .TASK_DIR }} && terraform apply
  clean: git clean -fdX