# ------------------------------------------------------------
# This project is powered by: https://taskfile.dev
# ------------------------------------------------------------
version: 3
env: # <-- Project Configuration (required ENV vars)
  ENVIRONMENT: "{{ .ENVIRONMENT }}"
tasks:
  create: ./create-cluster
  init: terraform init
  plan: terraform plan
  apply: terraform apply
  destroy: terraform destroy
